#pragma once

#include "util/unit.h"

#include "engine/math/matrix.h"

PROTOTYPE_TEST(TRANSPOSE_MATRIX_FN(3, 1));

PROTOTYPE_TEST(MULTIPLY_MATRIX_FN(2, 2, 2));
PROTOTYPE_TEST(MULTIPLY_MATRIX_FN(3, 3, 3));
PROTOTYPE_TEST(MULTIPLY_MATRIX_FN(3, 3, 1));

PROTOTYPE_TEST(PAD_MATRIX_FN(2, 2, 3, 3));
PROTOTYPE_TEST(PAD_MATRIX_FN(2, 1, 3, 1));
PROTOTYPE_TEST(PAD_MATRIX_FN(3, 1, 2, 1));
